
# Read the Docs configuration file for Sphinx projects

# Required
version: 2

# Set the OS and Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the "docsrc/" directory with Sphinx
sphinx:
   configuration: docsrc/conf.py

# pyZscaler doc build requirements
python:
  install:
  - requirements: dev_requirements.txt